onboarding = false

[theme]
name = "catppuccin"

[keys]
help = "prefix+?"
settings = "prefix+s"
detach = "prefix+q"
reload_config = "prefix+shift+r"

goto = "prefix+g"
open_notification_target = "prefix+o"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"
zoom = ["prefix+z", "prefix+f"]

close_workspace = "prefix+shift+d"
new_workspace = "prefix+shift+n"
next_workspace = ["ctrl+alt+down", "ctrl+alt+j"]
previous_workspace = ["ctrl+alt+up", "ctrl+alt+k"]
rename_workspace = "prefix+shift+w"
switch_workspace = "prefix+shift+1..9"
workspace_picker = "prefix+w"

new_worktree = "prefix+shift+g"
open_worktree = "prefix+shift+o"
# remove_worktree = ""

previous_agent = ["ctrl+alt+shift+up", "ctrl+alt+shift+k"]
next_agent = ["ctrl+alt+shift+down", "ctrl+alt+shift+j"]
focus_agent = "prefix+alt+1..9"

new_tab = "prefix+c"
rename_tab = "prefix+shift+t"
previous_tab = ["ctrl+alt+left", "ctrl+alt+h"]
next_tab = ["ctrl+alt+right", "ctrl+alt+l"]
switch_tab = "prefix+1..9"
close_tab = "prefix+shift+x"

edit_scrollback = "prefix+e"
rename_pane = "prefix+shift+p"
focus_pane_left = ["prefix+h", "prefix+left", "ctrl+shift+h", "ctrl+shift+left"]
focus_pane_down = ["prefix+j", "prefix+down", "ctrl+shift+j", "ctrl+shift+down"]
focus_pane_up = ["prefix+k", "prefix+up", "ctrl+shift+k", "ctrl+shift+up"]
focus_pane_right = [
  "prefix+l",
  "prefix+right",
  "ctrl+shift+l",
  "ctrl+shift+right",
]
cycle_pane_next = "prefix+tab"
cycle_pane_previous = "prefix+shift+tab"
last_pane = "ctrl+`"
close_pane = "prefix+x"
split_vertical = ["prefix+backslash"]
split_horizontal = ["prefix+minus"]

navigate_workspace_up = "up"
navigate_workspace_down = "down"
navigate_pane_left = "h"         # left arrow always focuses the pane to the left
navigate_pane_down = "j"
navigate_pane_up = "k"
navigate_pane_right = "l"        # right arrow always focuses the pane to the right

[[keys.command]]
key = ["ctrl+alt+g"]
# type = "shell" runs detached in the background.
# type = "pane" opens a temporary pane and closes it when the command exits.
type = "pane"
command = "lazygit"
description = "run lazygit"

[[keys.command]]
key = ["prefix+alt+g"]
type = "shell"
# command = "fish -lc 'herdr_tab_git'"
command = "HERDR_ENV=1 fish -lc 'herdr_tab_git'"
description = "open git tab"

[[keys.command]]
key = ["prefix+alt+r", "ctrl+alt+r"]
type = "pane"
command = "tuicr-current auto"
description = "review current change with tuicr"

[[keys.command]]
key = "prefix+alt+w"
type = "pane"
command = "fish -lc 'herdr_wt_switch'"
description = "switch/create worktree with wt and open in herdr"

[ui]
accent = "magenta"
agent_panel_scope = "all"
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

# Play sounds when agents change state in background workspaces
[ui.sound]
enabled = true

[experimental]
# Save recent pane screen history across full server restarts.
pane_history = false
