# https://docs.atuin.sh/configuration/config
enter_accept = false
filter_mode_shell_up_key_binding = "directory"
invert = true
keymap_mode = "vim-insert"
update_check = false

[sync]
records = true

[keys]
scroll_exits = false
