[/]
clock-show-seconds=false
clock-show-weekday=false
color-scheme='prefer-dark'
cursor-theme='Colloid-cursors'
document-font-name='Roboto 11'
font-antialiasing='grayscale'
font-hinting='slight'
font-name='Roboto 11'
gtk-theme='Catppuccin-Mocha-Standard-Flamingo-dark'
monospace-font-name='FiraCode Nerd Font Mono 10'
show-battery-percentage=true
