[gtk-variants]
day='Catppuccin-Frappe-Standard-Flamingo-dark'
enabled=true
night='Catppuccin-Mocha-Standard-Flamingo-dark'

[shell-variants]
day='Catppuccin-Frappe-Standard-Flamingo-dark'
enabled=true
night='Catppuccin-Mocha-Standard-Flamingo-dark'

[time]
manual-schedule=true
nightthemeswitcher-ondemand-keybinding=['<Shift><Super>t']
sunset=19.0
