#!/usr/bin/env zsh

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

source "${HOME}/.zsh/is_has.zsh"

function setenv() { export "$1=$2"; }

_SETENV="${HOME}/.setenv"
if [[ -f "${_SETENV}" ]]
then
  source "${_SETENV}"
else
  echo "⚠ '${_SETENV}' not found!"
fi

#  ╭──────────────────────────────────────────────────────────╮
#  │ Tilix                                                    │
#  ╰──────────────────────────────────────────────────────────╯
if [ -n "${TILIX_ID}" ] || [ -n "${VTE_VERSION}" ]; then
  [ -f /etc/profile.d/vte.sh ] && source /etc/profile.d/vte.sh
fi

#  ╭──────────────────────────────────────────────────────────╮
#  │ https://github.com/zplug/zplug                           │
#  ╰──────────────────────────────────────────────────────────╯
if [[ ! -d "${ZPLUG_HOME}" ]]; then
  git clone --depth=1 https://github.com/zplug/zplug "${ZPLUG_HOME}" && \
    source "${ZPLUG_HOME}/init.zsh" && zplug update --self-manage
else
  source "${ZPLUG_HOME}/init.zsh"
fi

source "${HOME}/.zsh/path.zsh"
source "${HOME}/.zsh/gpg.zsh"
source "${HOME}/.zsh/history.zsh"
source "${HOME}/.zsh/spectrum.zsh"
source "${HOME}/.zsh/prompt.zsh"
source "${HOME}/.zsh/zsh_hooks.zsh"

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi
zplug load # --verbose

if [ "${ZPLUG_UPDATE}" = true ] ; then
  zplugs_install
  zplug update
fi

#  ╭──────────────────────────────────────────────────────────╮
#  │ post zplug load                                          │
#  ╰──────────────────────────────────────────────────────────╯
source "${HOME}/.zsh/colors.zsh"
source "${HOME}/.zsh/completion.zsh"
source "${HOME}/.zsh/app_init.zsh"
source "${HOME}/.zsh/bindkeys.zsh"
source "${HOME}/.zsh/aliases.zsh"
source "${HOME}/.zsh/functions.zsh"
source "${HOME}/.zsh/packages.zsh"
source "${HOME}/.zsh/setopt.zsh"

# untracked dotfile for sensative exports, etc
if [[ -f ~/.untracked.zsh ]]
then
  source ~/.untracked.zsh
fi

# work dotfile for work related exports, etc
if [[ -f ~/.work.zsh ]]
then
  source ~/.work.zsh
fi
