#:schema https://mise.jdx.dev/schema/mise.json

[settings]
experimental = true
lockfile = true
locked_verify_provenance = true
## cannot enforce until all used backends support lock (npm/pipx)
## https://mise.jdx.dev/dev-tools/mise-lock.html#backend-support
locked = true

# Optional “paranoid” hardening + signature verification
paranoid = true   # extra-secure behavior (hooks/tasks etc.) :contentReference[oaicite:8]{index=8}
gpg_verify = true # verify signatures for supported tools :contentReference[oaicite:9]{index=9}

[settings.aqua]
baked_registry = true
cosign = true
minisign = true
slsa = true

[settings.github]
credential_command = "github-token-get"

[settings.npm]
package_manager = "bun"

[hooks]
postinstall = "mise-completions-sync" # installed via aqua

[tools]

bun = "1.3.13"
go = "1.26.2"
node = "24.15.0"
rust = "1.95.0"

# linters & related
"aqua:rhysd/actionlint" = "1.7.12"
"go:golang.org/x/tools/gopls" = "0.21.1"
"npm:@commitlint/cli" = "20.5.0"
"npm:@fsouza/prettierd" = "0.27.0"
"npm:bash-language-server" = "5.6.0"
"npm:cspell" = "10.0.0"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:jsonlint" = "1.6.3"
"npm:markdown-toc" = "1.2.0"
"npm:markdownlint-cli" = "0.48.0"
"npm:prettier" = "3.8.3"
"npm:pyright" = "1.1.409"
"npm:sql-formatter" = "15.7.3"
"npm:sql-language-server" = "1.7.1"
"npm:stylelint" = "17.8.0"
"npm:textlint" = "15.5.4"
"pipx:ansible-lint" = "26.4.0"
"pipx:beautysh" = "6.4.3"
"pipx:gitlint-core" = "0.19.1"
"pipx:isort" = "8.0.1"
"pipx:mypy" = "1.20.1"
"pipx:pyproject-flake8" = "7.0.0"
"pipx:ruff-lsp" = "0.0.62"
"pipx:semgrep" = "1.160.0"
"pipx:sqlfluff" = "4.1.0"
"pipx:yamllint" = "1.38.0"

# tools
"aqua:google/go-containerregistry" = "0.21.5"
"aqua:int128/ghcp" = "1.15.3"
"aqua:mfontanini/presenterm" = "0.16.1"
"aqua:sethvargo/ratchet" = "0.11.4"
"aqua:sst/opencode" = "1.14.19"
"aqua:vercel-labs/agent-browser" = "0.26.0"
"github:always-further/nono" = "0.38.0"
"npm:@fission-ai/openspec" = "1.3.1"
"npm:@google/gemini-cli" = "0.38.2"
"npm:ccusage" = "18.0.11"
"npm:opkg" = "0.11.1"
"aqua:alexpasmantier/television" = "0.15.6"
