# Extension name = store owner (not necessarily the manifest author).
[vicinae.extensions.raycast]
gif-search = "josephschmitt"
notion = "notion"
slackmojis = "timoransky"
todoist = "doist"

[vicinae.extensions.vicinae]
nerdfont-search = "fbosch"
niri = "knoopx"
podman = "knoopx"
timer = "harshnarayanjha"
