[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 5
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
