theme = "catppuccin-mocha"

appearance = "system"
theme_dark = "catppuccin-mocha"
theme_light = "catppuccin-latte"

show_file_list = true
diff_view = "unified" # "side-by-side"
wrap = true

comment_types = [
  { id = "note", label = "question", definition = "ask for clarification", color = "yellow" },
  { id = "suggestion", definition = "possible improvements" },
  { id = "issue", definition = "problems to fix" },
  { id = "praise", definition = "positive feedback" },
  { id = "nit", label = "nitpick", definition = "small optional tweaks", color = "#d19a66" },
]
