$base = rgb({{ substr 1 7 .bg }})
$surface0 = rgb({{ substr 1 7 .bg_alt }})
$text = rgb({{ substr 1 7 .fg }})
$accent = rgb({{ substr 1 7 .accent }})
$red = rgb({{ substr 1 7 .red }})
$yellow = rgb({{ substr 1 7 .yellow }})
