# https://worktrunk.dev/config/

# assumes bare clone for worktrees
worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"
skip-shell-integration-prompt = true

[post-start]
copy = "command -v thts && thts init --no-agents --force"

[projects]
