---
name: update-aqua-checksums
on:
  pull_request:
    paths:
      - aqua/aqua.yaml
      - aqua/aqua-checksums.json
jobs:
  update-aqua-checksums:
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@v1.0.0 # renovate: depName=aquaproj/update-checksum-workflow
    permissions:
      contents: read
    with:
      aqua_version: v2.28.0 # renovate: depName=aquaproj/aqua
      prune: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
