---
name: chezmoi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: dagger call init
        # yamllint disable-line rule:line-length
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # renovate: datasource=github-releases depName=dagger/dagger
          version: v0.21.4
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          module: .
          call: init
