---
name: Check Semantic Pull Request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions: read-all
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
