name: trunk.io
on:
  push:
    branches:
      - main
  # yamllint disable-line rule:empty-values
  pull_request:
jobs:
  getModules:
    name: trunk.io
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Trunk
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
