name: trunk.io
on:
  push:
    branches:
      - main
  # yamllint disable-line rule:empty-values
  pull_request:
jobs:
  getModules:
    name: trunk.io
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Trunk
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
