name: trunk.io
on:
  push:
    branches:
      - main
  # yamllint disable-line rule:empty-values
  pull_request:
jobs:
  getModules:
    name: trunk.io
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Trunk
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
