name: Check
on:
  push:
    branches:
      - main
  # yamllint disable-line rule:empty-values
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  getModules:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trunk
        uses: trunk-io/trunk-action@v1
