---
on:
  push:
    branches:
      - main
name: release-please
permissions: read-all
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        with:
          release-type: go
          package-name: dots
