---
on:
  push:
    branches:
      - main
name: release-please
permissions: read-all
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          release-type: go
          package-name: dots
